spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/outboxdb
    username: your_username
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

outbox:
  retry:
    limit: 3

opentelemetry:
  enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
