apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
spec:
  tls:
    - hosts:
        - harvester.k8s.ct
      secretName: wildcard-k8s-ct-tls
  rules:
    - host: harvester.k8s.ct
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 80
