replicaCount: 1
image:
  registry: registry.k8s.ct
  repository: outbox-harvester
  tag: master.20250906.13
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1
    memory: 1Gi
